# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Build Docker Images
          command: |
            echo "Docker build"
            docker build -t udagram-api-feed:v1 ./udagram-api-feed
            docker build -t udagram-api-user:v1 ./udagram-api-user
            docker build -t udagram-frontend:v1 ./udagram-frontend
            docker build -t udagram-reverseproxy:v1 ./udagram-reverseproxy
            echo "Docker tag"
            docker tag udagram-api-feed:v1 quyennt201/udagram-api-feed:v1
            docker tag udagram-api-user:v1 quyennt201/udagram-api-user:v1
            docker tag udagram-frontend:v1 quyennt201/udagram-frontend:v1
            docker tag udagram-reverseproxy:v1 quyennt201/udagram-reverseproxy:v1
      - run:
          name: Push Docker Images
          command: |
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            echo "Pushing image to Docker Hub"
            docker push quyennt201/udagram-api-feed:v1
            docker push quyennt201/udagram-api-user:v1
            docker push quyennt201/udagram-frontend:v1
            docker push quyennt201/udagram-reverseproxy:v1

workflows:
  build-workflow:
    jobs:
      - build